name: conallservs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  provider: ^6.0.5
  image_picker: ^1.1.2
  firebase_core: ^2.20.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.20.0
  firebase_storage: ^11.2.4
  google_sign_in: ^6.2.1

assets:
  - lib/assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
